version: '3.7'
services:
  api:
    image: fischettij/pixowlgram:v1
    restart: unless-stopped
    ports:
      - '8080:9001'
    environment:
      NODE_ENV: production
      SERVER_PORT: 9001
      ACCESS_TOKEN_SECRET: H1mWcj3Uyj3eG9ez
      DATABASE_URL: 'postgres://pixowlgram:f263P9IrZRKqwxnR@db:5432/pixowlgram'
    volumes:
      - ./logs/:/opt/app/logs/
    depends_on:
      - db
      - migration
  migration:
    image: fischettij/pixowlgram:v1
    command: ['./wait-for-it.sh', 'db:5432', '--', 'npm', 'run', 'db:migrate']
    environment:
      NODE_ENV: production
      DATABASE_URL: 'postgres://pixowlgram:f263P9IrZRKqwxnR@db:5432/pixowlgram'
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: pixowlgram
      POSTGRES_PASSWORD: 'f263P9IrZRKqwxnR'
    restart: unless-stopped
